{% set name = "python-barcode" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 241b34aa5c5cb6a9889882f9409b0182903a2c5d19b4218be3609cdbbd5ffdf9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - python-barcode = barcode.pybarcode:main


requirements:
  host:
    - python >=3.5
    - pip
    - setuptools_scm
  run:
    - python
    - pillow

test:
  commands:
    - python-barcode --help
  imports:
    - barcode

about:
  home: http://github.com/WhyNotHugo/python-barcode
  license: MIT
  license_family: MIT
  license_file: LICENCE
  summary: This library provides a simple way to create barcodes using only the Python standard lib
  dev_url: http://github.com/WhyNotHugo/python-barcode

extra:
  recipe-maintainers:
    - sodre
